apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: default
  labels:
    app: front-end
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer