apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: default
  labels:
    app: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: ghcr.io/sysadmin29/front-end:v1.0.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 128Mi
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret